/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\Skyscraper.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Skyscraper(props) {
    const { nodes, materials } = useGLTF("/models/Skyscraper.glb")
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.033}>
                <mesh geometry={nodes['Flat_Grass_01_-_Default_0_1'].geometry} material={materials.Material} castShadow />
                <mesh geometry={nodes['Flat_Grass_01_-_Default_0_2'].geometry} material={materials.window} castShadow />
                <mesh geometry={nodes['Flat_Grass_01_-_Default_0_3'].geometry} material={materials.leaves} castShadow />
                <mesh geometry={nodes['Flat_Grass_01_-_Default_0_4'].geometry} material={materials['dark-leaves']} castShadow />
                <mesh geometry={nodes['Flat_Grass_01_-_Default_0_5'].geometry} material={materials.terrain} castShadow />
                <mesh geometry={nodes['Flat_Grass_01_-_Default_0_6'].geometry} material={materials.border} castShadow />
            </group>
        </group>
    )
}

useGLTF.preload("/models/Skyscraper.glb")
